disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "The Perl and Raku Foundation"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "perl-logo-32x104_orig.png"
description = "The Perl Foundation is dedicated to the advancement of the Perl and Raku programming language. We seek to do this through open discussion, collaboration, design, and code."

["params.author"]
name = "Yet Another Society"
